using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Windows;
using System.Windows.Controls;

namespace ListOfBasesUsers
{
    /// <summary>
    /// Логика взаимодействия для MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {

        private IEnumerable<RowBase> _listBases = new List<RowBase>();
        private IEnumerable<RowBase> _listBasesFiltering = new List<RowBase>();
        private List<RowBase> _selectedBases = new List<RowBase>();

        private bool _filterIsNotList = false;
        private string _nameRowIsNotList = "нет в списке";

        public MainWindow()
        {
            InitializeComponent();
        }

        private void WindowMain_Loaded(object sender, RoutedEventArgs e)
        {
            if (IsLoaded)
            {
                GetListUser();
                SetCurrentUser();
                SetVisibleBtnDelCacheSelected();
                ChangeItemSoursedgTable();
                SetVisibleElements();
            }
        }

        #region main menu

        private void CbUser_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            FillTable();
            UpdateSize();
        }

        private void BtnUpdate_Click(object sender, RoutedEventArgs e)
        {
            FillTable();
            UpdateSize();
        }

        private void BtnUpdateSize_Click(object sender, RoutedEventArgs e)
        {
            UpdateSize();
        }

        private void BtnDelCacheSelected_Click(object sender, RoutedEventArgs e)
        {
            if (_selectedBases.Count == 0)
            {
                Dialog.ShowMessage("Не выбраны строки для удаления.");
                return;
            }

            if (!Dialog.DialogQuestion($"Удалить кеши для баз в количестве - {_selectedBases.Count} шт."))
                return;

            new DirFile().DeleteCatalogCache(_selectedBases);

            if (Dialog.DialogQuestion("Каталоги удалены.\nПересчитать размеры кеша?"))
                UpdateSize();

        }

        private void BtnFilterIsNotList_Click(object sender, RoutedEventArgs e)
        {
            _filterIsNotList = !_filterIsNotList;
            ChangeItemSoursedgTable();
        }

        #endregion

        #region datagrid Table

        private void DgTable_AutoGeneratedColumns(object sender, EventArgs e)
        {

            foreach (PropertyInfo propInfo in new RowBase().GetType().GetProperties())
            {

                DataGridColumn column = dgTable.Columns.FirstOrDefault(f => (string)f.Header == propInfo.Name);
                if (column != null)
                {

                    var propAttribute = propInfo.GetCustomAttributes<PropertiesColumnsAttribute>();

                    if (propAttribute.Count() > 0)
                    {

                        var attribute = propAttribute.First();

                        column.Header = attribute.HeaderName;
                        column.Visibility = attribute.VisibleColumn ? Visibility.Visible : Visibility.Hidden;

                        if (!string.IsNullOrWhiteSpace(attribute.SortMemberPath))
                            column.SortMemberPath = attribute.SortMemberPath;

                        if (attribute.SortDirection != null)
                            column.SortDirection = attribute.SortDirection;

                    }

                }

            }

        }

        private void DgTable_SelectedCellsChanged(object sender, SelectedCellsChangedEventArgs e)
        {
            SetVisibleBtnDelCacheSelected();
            SetVisibleElements();
            SetVisibleTotalInSelected();
        }

        #endregion

        #region datagrid Table ContextMenu

        private void DgTableOpenDirectoryLocal_Click(object sender, RoutedEventArgs e)
        {

            string pathCache = GetPathCacheCurrentRow(TypeCache.Local);
            if (string.IsNullOrWhiteSpace(pathCache))
            {
                Dialog.ShowMessage("Каталог кеша (Local) не найден");
                return;
            }

            new DirFile(pathCache).OpenDirectory();

        }

        private void DgTableOpenDirectoryAppData_Click(object sender, RoutedEventArgs e)
        {

            string pathCache = GetPathCacheCurrentRow(TypeCache.AppData);
            if (string.IsNullOrWhiteSpace(pathCache))
            {
                Dialog.ShowMessage("Каталог кеша (AppData) не найден");
                return;
            }

            new DirFile(pathCache).OpenDirectory();

        }

        private void DgTableClearCache_Click(object sender, RoutedEventArgs e)
        {
            ClearCacheRow(TypeCache.Local);
            ClearCacheRow(TypeCache.AppData);

            if (Dialog.DialogQuestion("Каталог удален.\nПересчитать размеры кеша?"))
                UpdateSize();
        }

        private void ClearCacheRow(TypeCache typeCache)
        {
            string pathCache = GetPathCacheCurrentRow(typeCache);
            if (string.IsNullOrWhiteSpace(pathCache))
                return;

            new DirFile(pathCache).DeleteCatalogCache();
        }

        #endregion

        #region private methods

        private void GetListUser()
        {

            SetValueStatusBar("Загрузка списка пользователей...");

            cbUser.Items.Clear();
            foreach (string item in new DirFile().GetListUsers())
                cbUser.Items.Add(item);

            SetValueStatusBar();

        }

        private void SetCurrentUser()
        {
            cbUser.SelectedValue = DefaultValues.nameCurrentUser;
        }

        private void FillTable()
        {

            SetValueStatusBar("Получение списка баз...");

            string selectedName = cbUser.SelectedItem?.ToString();

            if (!string.IsNullOrWhiteSpace(selectedName))
                _listBases = new ListIbases(selectedName).GetListBases(this);

            ChangeItemSoursedgTable();

            SetValueStatusBar();

        }

        private void UpdateSize()
        {

            if (_listBases.Count() == 0)
                return;

            SetValueStatusBar("Получение размеров кеша...");

            string selectedName = cbUser.SelectedItem?.ToString();
            ulong totalByte = 0;
            string total = "";

            if (!string.IsNullOrWhiteSpace(selectedName))
                new ListIbases(selectedName).ReadCache(ref _listBases, ref totalByte, ref total);

            txtTotalByte.Text = totalByte.ToString();
            txtTotal.Text = total;

            ChangeItemSoursedgTable();

            SetValueStatusBar();

        }

        private void SetValueStatusBar(string text = "")
        {
            //sbItem.Text = text;
        }

        private string GetPathCacheCurrentRow(TypeCache typeCache)
        {

            string pathCache = "";

            if (typeCache == TypeCache.Local)
                pathCache = ((RowBase)dgTable.CurrentItem).PathCacheLocal;
            else if (typeCache == TypeCache.AppData)
                pathCache = ((RowBase)dgTable.CurrentItem).PathCacheAppData;
            else
                return pathCache;

            if (pathCache == null)
            {
                //Dialog.ShowMessage("Каталог кеша не найден.");
                return null;
            }

            return pathCache;

        }

        private void SetVisibleBtnDelCacheSelected()
        {

            _selectedBases.Clear();

            foreach (RowBase item in dgTable.SelectedItems)
            {

                if (item.SizeByte > 0)
                    _selectedBases.Add(item);

            }
            
            Visibility newVisibility;
            if (_selectedBases.Count > 1)
            {
                newVisibility = Visibility.Visible;
            }
            else
            {
                newVisibility = Visibility.Hidden;
            }


            btnDelCacheSelected.Visibility = newVisibility;


        }

        private void SetVisibleElements()
        {

            bool lastElementHide = false;
            double lastPosition = 0;
            for (int i = 0; i < grMainMenu.Children.Count; i++)
            {

                UIElement currentItem = grMainMenu.Children[i];
                FrameworkElement currentElement = (FrameworkElement)currentItem;

                if (currentItem.Visibility == Visibility.Visible)
                {

                    if (lastElementHide
                        || lastPosition == (currentElement.Width + currentElement.Margin.Left))
                        currentElement.Margin = new Thickness(lastPosition + 10, 0, 0, 0);

                    lastPosition = currentElement.Margin.Left + currentElement.Width;
                    lastElementHide = false;

                }
                else
                {
                    lastElementHide = true;
                }

            }

            SetVisibleTotalInSelected();

        }

        private void ChangeItemSoursedgTable()
        {

            if (_filterIsNotList)
            {

                List<RowBase> list = new List<RowBase>();

                foreach (RowBase item in _listBases)
                {

                    if (_filterIsNotList && item.Name != _nameRowIsNotList)
                        continue;

                    list.Add(item);

                }

                _listBasesFiltering = list;

                dgTable.ItemsSource = _listBasesFiltering;

            }
            else
                dgTable.ItemsSource = _listBases;



            int font = _filterIsNotList ? 500 : 1;

            btnFilterIsNotList.FontWeight = FontWeight.FromOpenTypeWeight(font);

        }

        private void SetVisibleTotalInSelected()
        {

            ulong totalByte = 0;

            foreach (RowBase item in _selectedBases)
            {
                totalByte += item.SizeByte;
            }

            string total = new DirFile().GetSizeFormat(totalByte);

            txtTotalByteSelected.Text = totalByte.ToString();
            txtTotalSelected.Text = total;

            grSelectedTotal.Visibility = _selectedBases.Count > 1 ? Visibility.Visible : Visibility.Hidden;

        }

        #endregion

    }
}
